spring:
  profiles:
    active: pro
---
spring:
  application:
    name: SpringCloud-3305
  profiles: pro
server:
  port: 6666
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
server:
  port: 7777
spring:
  application:
    name: SpringCloud-3355
  profiles: dev
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
    #暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
