spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 3305
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
server:
  port: 3355
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
spring:
  profiles: test
    #暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
